CREATE TABLE portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    market VARCHAR(2) NOT NULL,
    stock_name VARCHAR(100) NOT NULL,
    average_price DECIMAL(19, 2) NOT NULL,
    current_price DECIMAL(19, 2) NOT NULL,
    quantity BIGINT NOT NULL
);

CREATE TABLE realized_gain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    stock_name VARCHAR(100) NOT NULL,
    gain_amount DECIMAL(19, 2) NOT NULL,
    realized_date DATE NOT NULL
);
